// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-elEl7414WSu0W0V08qs1PIH3LODvp-w',
    appId: '1:97667049659:web:cbba04bc701b1b44b9e19e',
    messagingSenderId: '97667049659',
    projectId: 'image-conversion-e3ed9',
    authDomain: 'image-conversion-e3ed9.firebaseapp.com',
    storageBucket: 'image-conversion-e3ed9.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJhSV97SnEi1TVfDZPYH9Y4jPcsjXZaC8',
    appId: '1:97667049659:android:2bdd437eb70656c4b9e19e',
    messagingSenderId: '97667049659',
    projectId: 'image-conversion-e3ed9',
    storageBucket: 'image-conversion-e3ed9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCpyIhNE9jnlv-WYKi5DV4-ixp7491dbUI',
    appId: '1:97667049659:ios:aaebb30dd2fbb347b9e19e',
    messagingSenderId: '97667049659',
    projectId: 'image-conversion-e3ed9',
    storageBucket: 'image-conversion-e3ed9.appspot.com',
    iosBundleId: 'com.example.text',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCpyIhNE9jnlv-WYKi5DV4-ixp7491dbUI',
    appId: '1:97667049659:ios:999cffe39cdcf986b9e19e',
    messagingSenderId: '97667049659',
    projectId: 'image-conversion-e3ed9',
    storageBucket: 'image-conversion-e3ed9.appspot.com',
    iosBundleId: 'com.example.text.RunnerTests',
  );
}
